
//复习资料
var dk_file = [];
//资料类型（word/ppt/excel),资料名称,上传者,授课老师,学期,下载量
//全部 按下载热度
dk_file[0] = [
	{
		type:'word',
		name:'【石油工程】物理题课后答案',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'word',
		name:'油气田开发地质',
		author:'特色凉菜',
		teacher:'李佩佩',
		semester:'2014(上）',
		download:'550'
	},
	{
		type:'ppt',
		name:'流体力学第一章ppt',
		author:'特色凉菜',
		teacher:'范冰冰',
		semester:'2014(下)',
		download:'545'
	},
	{
		type:'pdf',
		name:'采矿学第一章知识点',
		author:'红烧牛肉',
		teacher:'李晨',
		semester:'2014(下)',
		download:'540'
	},
	{
		type:'ppt',
		name:'资源勘查期末考试习题',
		author:'红烧牛肉',
		teacher:'李晨',
		semester:'2014(下)',
		download:'538'
	},
	{
		type:'word',
		name:'【石油工程】物理题课后答案',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'532'
	},
	{
		type:'word',
		name:'油气田开发地质',
		author:'特色凉菜',
		teacher:'李佩佩',
		semester:'2014(上）',
		download:'531'
	},
	{
		type:'ppt',
		name:'流体力学第一章ppt',
		author:'特色凉菜',
		teacher:'范冰冰',
		semester:'2014(下)',
		download:'525'
	},
	{
		type:'word',
		name:'采矿学第二章知识点',
		author:'红烧牛肉',
		teacher:'蔡徐坤',
		semester:'2014(下)',
		download:'520'
	},
	{
		type:'ppt',
		name:'资源勘查期末考试习题',
		author:'红烧牛肉',
		teacher:'李晨',
		semester:'2014(下)',
		download:'510'
	},
	{
		type:'word',
		name:'【石油工程】物理题课后答案',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'480'
	},
	{
		type:'word',
		name:'油气田开发地质',
		author:'特色凉菜',
		teacher:'李佩佩',
		semester:'2014(上）',
		download:'476'
	},
	{
		type:'ppt',
		name:'流体力学第一章ppt',
		author:'特色凉菜',
		teacher:'范冰冰',
		semester:'2014(下)',
		download:'462'
	},
	{
		type:'pdf',
		name:'采矿学第二章知识点',
		author:'红烧牛肉',
		teacher:'蔡徐坤',
		semester:'2014(下)',
		download:'435'
	},
	{
		type:'pdf',
		name:'资源勘查期末考试习题',
		author:'红烧牛肉',
		teacher:'李晨',
		semester:'2014(下)',
		download:'425'
	},
	{
		type:'pdf',
		name:'【石油工程】物理题课后答案',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'412'
	},
	{
		type:'word',
		name:'油气田开发地质',
		author:'特色凉菜',
		teacher:'李佩佩',
		semester:'2014(上）',
		download:'400'
	},
	{
		type:'ppt',
		name:'流体力学第一章ppt',
		author:'特色凉菜',
		teacher:'范冰冰',
		semester:'2014(下)',
		download:'396'
	},
	{
		type:'pdf',
		name:'采矿学第二章知识点',
		author:'红烧牛肉',
		teacher:'蔡徐坤',
		semester:'2014(下)',
		download:'386'
	},
	{
		type:'ppt',
		name:'资源勘查期末考试习题',
		author:'红烧牛肉',
		teacher:'李晨',
		semester:'2014(下)',
		download:'300'
	}
];
//石油工程
dk_file[1] = [
	{
		type:'word',
		name:'【石油工程】物理题课后答案',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'word',
		name:'油气田开发地质',
		author:'特色凉菜',
		teacher:'李佩佩',
		semester:'2014(上）',
		download:'550'
	},
	{
		type:'ppt',
		name:'流体力学第一章ppt',
		author:'特色凉菜',
		teacher:'范冰冰',
		semester:'2014(下)',
		download:'545'
	},
	{
		type:'pdf',
		name:'油气开发课后习题答案',
		author:'红烧牛肉',
		teacher:'李晨',
		semester:'2014(下)',
		download:'300'
	},
	{
		type:'word',
		name:'流体力学期末考试习题',
		author:'红烧牛肉',
		teacher:'李晨',
		semester:'2014(下)',
		download:'280'
	},
	{
		type:'ppt',
		name:'渗透力学第一章',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'250'
	},
	{
		type:'ppt',
		name:'渗透力学第二章',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'223'
	},
	{
		type:'ppt',
		name:'渗透力学第三章',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'210'
	},
	{
		type:'ppt',
		name:'渗透力学第四章',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'201'
	},
	{
		type:'word',
		name:'钻井工程课后答案',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'199'
	},
	{
		type:'pdf',
		name:'采油工程课后习题答案',
		author:'红烧牛肉',
		teacher:'李晨',
		semester:'2014(下)',
		download:'180'
	},
	{
		type:'pdf',
		name:'油田化学课后习题答案',
		author:'红烧牛肉',
		teacher:'李晨',
		semester:'2014(下)',
		download:'176'
	}
];
//采矿工程
dk_file[2] = [
	{
		type:'word',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'word',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'word',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'word',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'word',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'word',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'word',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'word',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'word',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'pdf',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'ppt',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'ppt',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'word',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'pdf',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'word',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	},
	{
		type:'ppt',
		name:'采矿工程资料',
		author:'久香冒菜',
		teacher:'安文雅',
		semester:'2015(上）',
		download:'556'
	}
];
//地矿工程
dk_file[3] = [
    {
        type:'word',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'ppt',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'pdf',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'ppt',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'pdf',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'ppt',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'pdf',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'pdf',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'ppt',
        name:'地质工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    }
];
//矿物加工
dk_file[4] = [
    {
        type:'ppt',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'pdf',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'pdf',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'pdf',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'ppt',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'ppt',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'pdf',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'ppt',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'pdf',
        name:'矿物加工资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    }
];
dk_file[5] = [
    {
        type:'word',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'pdf',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'ppt',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'ppt',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'pdf',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'ppt',
        name:'资源勘探资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    }
];
dk_file[6] = [
    {
        type:'pdf',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'pdf',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'ppt',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'pdf',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'ppt',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'ppt',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'pdf',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'word',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    },
    {
        type:'ppt',
        name:'勘探技术与工程资料',
        author:'久香冒菜',
        teacher:'安文雅',
        semester:'2015(上）',
        download:'556'
    }
];